### PR TITLE
Use acess token again

### PR DESCRIPTION
**Pull request by hkollmann**
If you use qx contrib update without an access token you limited to 50 requests.
With Access token the limit is 5000.

An undefined token is valid and leads to requests without Access token

### CODE REVIEW

**Comment by cboulanger** [comment]
Typically, you need to do `qx contrib update` only once per installation, and then again if a new contrib has been published. I understand that the limit could be reached (in case of many contribs or by just repeating use of `qx contrib update`).  However, requiring GitHub tokens looks like a show-stopper to me; then I'd rather change the way information is retrieved from GitHub. For the moment, the PR is fine with me, but I don't think that's the right aproach (having put it in in the first place).

**Comment by cboulanger** [comment]
If we use the Token, I suggest we put it into an environment variable and get rid of the get/set stuff, I just don't see the need for it any more, it duplicates functionality - we should use compile.json for configuration and not an additional mechanism.

**Comment by hkollmann** [comment]
The access token is not required - it's optional. So no show stopper. I agree to remove the set/unset stuff. What's about an optional parameter instead of the enviroment variable?

**Comment by cboulanger** [comment]
Good Idea! (this could still use a env variable via $ if one doesn't like to remember the token)

**Comment by cboulanger** [comment]
Would you be willing to change your PR to set the auth variable through a parameter instead?

**Comment by hkollmann** [comment]
I will - after learning to deal with the argv package

**Comment by hkollmann** [comment]
Done

**Review by cboulanger — CHANGES_REQUESTED** [review]
Thank you for the PR. Can you  remove the .vscode stuff, please? (you can leave the entry in the .gitignore). Also, it would be good if the commit only showed the changed lines - currently, the complete files are replaced line by line. I wonder why that is?

**Comment by hkollmann** [comment]
I create a new pull request #7. In this the linefeed are broken.

**Pull request closed without merging**
