### PR TITLE
adds support for `path-mappings` in compile.json, which allows applic…

### PR DESCRIPTION
**Pull request by johnspackman**
…ation URIs to be remapped to match the virtual filing system in the web server

### CODE REVIEW

**Review by hkollmann — CHANGES_REQUESTED** [review]
Could we have the static section in front of the file? All other commands have this. 
IMHO it's more readable first to have the command and then have the internals.

**Comment by cboulanger** [comment]
i would also support keeping the command section at the beginning, it gives a better overview of what's available.

**Comment by johnspackman** [comment]
I'd missed the fact that it was being moved up as well as being changed in the earlier commit otherwise I would have commented at the time, but I think that the opposite is true!  My rationale is that statics are usually at the bottom in most classes and typically have utility or other non-structural code in them - eg `getYargsCommand` is not much more than a large data structure which takes up 20% of the file, yet the rest of the code is where the functionality lies.  As there can  be only one `statics` section, any other utility methods would be dragged up there too.

I understand the argument about having yargs settings front and centre, and it is definitely better that all classes follow the same style, but as a general rule IMHO we should stay away from these kind of changes in future - they're very stylistic and open to interpretation, and (like a lot of lint rules) very much down to personal preference and not down to functionality.

**Comment by hkollmann** [comment]
As a general rule i agree. Only in this special case i thinks it's better to have getYargs Section in the front.

**Review by hkollmann — APPROVED** [review]

**Comment by johnspackman** [comment]
@cboulanger please can you review and merge if approved?

**Review by cboulanger — APPROVED** [review]

**Pull request merged**
