### PR TITLE
Add support for `qx serve`

### PR DESCRIPTION
**Pull request by johnspackman**
See also https://github.com/qooxdoo/qooxdoo-cli/issues/53

### CODE REVIEW

**Comment by oetiker** [comment]
hmmm is it intentional to add a ruby dependency with jekyll ?
 
if we actually need a static site generator, there are a bunch of node.js based options https://www.sitepoint.com/6-nodejs-static-site-generators/

**Comment by johnspackman** [comment]
jekyll is only required during development, and it seemed an appropriate choice because AFAICT it's pretty much mandatory for GitHub based websites (from what I read, you can use other products but it's discouraged because Jekyll support is always better).  

If we're going to have to learn additional third party apps & DSLs it's better to standardise on just the one - also in the case of Jekyll, any work on developing the theme will be common also.

This will come up again - for example, the API generator is HTML based also.  There isn't a lot of work in the Jekyll-specific stuff in this commit so there's no problem in switching to a different platform if necessary, it's just that IMHO Jekyll seems like a good fit at the moment.

**Comment by oetiker** [comment]
yes for github pages jekyll is 'the thing', I agree ... and it is an ok tool ... just the fact that we are in the process of  unburdening ourselves from the python requirement for qx dev ... so it seemed odd to the untrained eye to add ruby now instead ... especially in the guise of a multi dependency beast such as jekyll

**Comment by hkollmann** [comment]
I would prefer a node only version. I think npm install is much more easier than installing a lot of other tools.
We just eliminated gem/sass because of this.

**Comment by johnspackman** [comment]
Based on that list that @oetiker posted, my personal favourite so far is http://www.metalsmith.io/; I like that it has no bundling of other tools for templating etc, the docs are clear and easy to read, and it looks like a good fit.

I'll leave it a few days, but if there's no objections or recommendations for another product I'll switch from Jekyll to Metalsmith

**Comment by cboulanger** [comment]
Metalsmit looks very versatile. It could also be used for `qx create` and `qx add` if those commands need more power than they currently have.

**Comment by johnspackman** [comment]
closing, in favour of new PR about to be released

**Pull request closed without merging**
