### PR TITLE
Add mobile skeleton

### PR DESCRIPTION
**Pull request by hkollmann**
This add the mobile skeleton and add node-modules to .gitignore again

### CODE REVIEW

**Review by cboulanger — CHANGES_REQUESTED** [review]
Hi, this is great, thanks for your work on this. One small thing: could you  add the template variables in the file header (authors, copyrights etc.) like here : https://github.com/qooxdoo/qooxdoo-cli/blob/master/templates/skeleton/desktop/source/class/custom/Application.tmpl.js

**Comment by cboulanger** [comment]
Although while we're at this topic: Are files created by template "copyright" by the template file users? Shouldn't they be copyright by the person that wrote the template?

**Comment by oetiker** [comment]
I would make them copyright by the person using the template ... if need be I'll be glad to provide new public domain templates. After all the templates are supposed to build the basis for a new application. Don't want to encumber them with multiple copyright holders from the start.

**Comment by hkollmann** [comment]
Could we change the template variables to the javascript standard ${var} instead of $var? In this case we could easily use the templates from the framework

**Comment by cboulanger** [comment]
@oetiker You're right. Just wanted to be sure.

**Comment by cboulanger** [comment]
@hkollmann I wouldn't mind at all, this choice was more out of convenience. Can you cook up a quick `sed -i  's/xxx/yyy/'` recipe to replace it in the existing files & change the code which applies the variables to the templates.

**Comment by hkollmann** [comment]
Will be reopened after repo cleanup

**Comment by cboulanger** [comment]
Ok, cleanup is done.

**Pull request closed without merging**
