### PR TITLE
exchange 'path' with 'upath' module to normalize window paths to unix…

### PR DESCRIPTION
**Pull request by cboulanger**
… paths

### CODE REVIEW

**Comment by hkollmann** [comment]
Then you could remove the replace in Install.js, line 128:
          path : path_module.relative( process.cwd(), download_path + path_module.sep + path_module.dirname(path)).replace(/\\/g,"\/")

**Comment by cboulanger** [comment]
See #40

**Comment by cboulanger** [comment]
@johnspackman Can I go ahead?

**Review by johnspackman — APPROVED** [review]

**Comment by johnspackman** [comment]
2 approvals, merging, thank you @hkollmann !

**Pull request merged**
