### PR TITLE
Fix and improve qx contrib publish

### PR DESCRIPTION
**Pull request by cboulanger**
`qx contrib publish` was broken - this fixes it and adds some small improvements

### CODE REVIEW

**Review by johnspackman — APPROVED** [review]

**Comment by hkollmann** [comment]
You changed the parameters to have the long name in first. Could you do this for the other commands too? So that they look all equal?

**Comment by cboulanger** [comment]
You're right, but this should be a different PR. Would you create a seperate issue?

**Comment by hkollmann** [comment]
I create the issue - you spend half an hour to do the work? :-)

**Comment by cboulanger** [comment]
Yes, that's the idea :-) I'll do it tonight.

**Review by hkollmann — APPROVED** [review]

**Comment by hkollmann** [comment]
2 approves, merged

**Comment by hkollmann** [comment]
Thanks, @cboulanger

**Pull request merged**
